# PostgreSQL Connection (Render)
spring.datasource.url=${DB_HOST_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Render PORT
server.port=${PORT:8080}

# Mail (Render)
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
mail.from=${MAIL_FROM:noreply@physaflow.local}
