spring.application.name=calculator

# PostgreSQL Connection
spring.datasource.url=${DB_HOST_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

frontend.baseUrl=${FRONT_BASE_URL:http://localhost:3000}

# Mail (MailDev por defecto)
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
mail.from=${MAIL_FROM:noreply@physaflow.local}