# PostgreSQL Connection (Render)
spring.datasource.url=${DB_HOST_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Render PORT
server.port=${PORT:8080}

# Mail (SendGrid)
sendgrid.api-key=${SENDGRID_API_KEY}
mail.from=${MAIL_FROM:noreply@physaflow.local}
