# PostgreSQL Connection (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/physaflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true

# Mail (MailDev local)
spring.mail.host=localhost
spring.mail.port=1025
mail.from=noreply@physaflow.local
sendgrid.api-key=
